name:                           coverage

on:
  push:
    branches:
      - main
jobs:
  test:
    name:                       coverage
    runs-on:                    ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '-- --test-threads 12'
      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v2
        with:
          token: 7e6d0bd0-c7e8-44ce-a25b-a62d04f204d5
          fail_ci_if_error:     true